### ISSUE TITLE
ToDo: followups/extra

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#28]
* **Performance / File Sizes**
   * [x] size: trim css @media screen and window to max 2560 = 1440p: saved 95kb
   * [x] size: convert local files space->tab + other stuff (reduce line breaks, comments etc)
   * [x] performance: move js not autorun as last scripts loaded
   * [x] remove redundant `AdobeBlankRegular` fonts (they are identical): saved 102kb
   * [x] section and function timers to help improving perf

* **Functionality**
   * [x] re-run ability for each section

* **Anti-Fingerprinting Entropy**
   * [ ] detect randomizing audio [working and ready to deploy]
   * [ ] detect randomizing of clientrect in unicode glyphs test
   * [ ] detect randomizing canvas
   * [ ] detect randomizing domrect
   * [ ] detect randomizing in css line height when I fall back to clientrect

* **General**
   * [x] detect iframe error/blocking [and output as result]
   * [x] detect xhr error/blocking [and output as result]
   * [x] detect image error/blocking [and output as result]
      * e.g. the image in an iframe for the app language MediaDocument.properties
   * [x] detect when Cross-Origin-Request is blocked in FF68+ : namely with `file:///`
   * [x] denote `file:///` results [as these can differ when run over http*]
   * [x] remove iframes where possible for less breakage
      * moved to top document: widgets, font fallback, unicode glyphs, default font properties, woff2

* **Cosmetic**
   * [x] use `n/a` for `[test]` results when the test is not run (previous I used `no`) and remove clutter like `insecure content` or `file:///` - just use `n/a`
   * [x] use `failed` (+ error message if provided) or `success` for `[test]` results when a test is run (previously I used `no` or `yes`?)
   * [x] reduce "intro" paragraphs to under 275 chars see #32 
   * [x] RFP protection detection (where it makes sense)
      * where this is used, it must output either a red or green `[RFP]`, i.e lack of one = not checked
   * [x] TB protection detection (where it makes sense) - this is for items not covered by in FF RFP
      * green `TB` sprinkled throughout where it might make sense
      * e.g new window sizes, css-line heights, etc

* **Screen**
   * [x] add side channel devicePixelRatio leaks
   * [x] FS test: add output element dimensions, not just screen
   * [x] add malicious new window size test
   * [x] css media window/screen: use `min-`width, `min-`height, `min-`device-width, `min-`device-height
      * without `min-` output is affected by zoom
   * [x] for desktop only, add real time updates of screen metrics (i.e. resolutions, screen, window, viewport, full screen status)
   * [x] add warning panel height entropy in Tor Browser when entering full screen
   * [x] android: fix full screen test
   * [x] android: add keyboard height PoC
   * [x] android: add toolbar height PoC
   * [x] android: detect without user actions, the native resolution of the inner window
   * [x] android: when doing the new window test: detect if result is with or without the toolbar visible
   * [x] add matchMedia for screen and inner window - thanks kkapsner
   * [ ] android: keyboard PoC needs a tweak, if the keyboard is a little slow to appear e.g. on first appearance after opening Firefox, then I can end up with 0 pixels: instead start checking using a setInterval and keep checking until I detect a change and that change is static
   * [ ] android: Tor Browser: keyboard + toolbar height PoCs are whack because TB updates the viewport as you zoom
   * [ ] improve global zoom variable

* **User Agent**
   * [x] widgets
   * [x] scrollbar width: detect when a negative : e.g android
   * [x] css line height: add in document font blocking detection & logic, add in `TB` logic & `TB Linux` leaks, add in zoom variable for known results (TNR users `Win`, `Linux`), use decimal part logic for `Mac`, add in non- zoom for `Android` (after 19.5 in Linux), add `known` metric vs logical `guess` notation
   * [x] css line height: fall back to clientrect() when getComputedStyle returns `normal`

* **Math**
   * [x] FF68+ : `expm1(1)` was affected on some platforms & architectures
   * [ ] TB9+ based on ESR68 : `expm1(1)` changes .. waiting to check

* **Language**
   * [x] add in app language PoC for the two DTD locale leaks
   * [x] add in app language PoC for dom.properties
   * [x] add in app language PoC for MediaDocument.properties
   * [x] add in app language PoC for xmlparser.properties
   * [x] detect and output info for the bug fix for the two app language DTD leaks: they need to time out after excluding other possible blockers (such as iframes blocked etc). Add logic to make Tor Browser wait an extra second due to latency
   * [x] xmlparser: completely strip the location to make it shorter, portable/universal (hashing the en-US string)
   * [x] output red/green `[en-US]` for the app language tests: it can be subtle e.g `PNG Image` vs `Image PNG`, or `pixel` vs `pixels`
   * [x] add BigInt: FF68+
   * [x] move items to details, and output hashes instead
   * [x] add geo hash red/green notation (`FF default`, `TB default` or `unusual`)
   * [x] add reg/green `RFP` notation for the other hashes
   * [x] refine hash notation to show diff between `RFP` and `SPOOF ENGLISH`
   * [x] add Intl.NumberFormat(BigInt).FormatToParts: FF70+
   * [x] add BigInt.toLocaleString: FF70+
   * [ ] add Intl.NumberFormat: FF70+?

* **Headers**
   * [x] add in red/green RFP for network connection: i.e if netinfo is enabled, then parse the connection `type`

* **Canvas**
   * [x] FYI: https://privacycheck.sec.lrz.de/active/fp_c/fp_canvas.html
   * [x] output error info = more entropy value
   * [x] add `id`s so canvas can use generic `outputSection` function like everyone else
   * [ ] add in offscreenCanvas tests - see [1422862#c1](https://bugzilla.mozilla.org/show_bug.cgi?id=1422862#c1)
   * [ ] other detection tests: see [CB tests](https://canvasblocker.kkapsner.de/test/detectionTest.html)

* **DOMRect**
   * [x] domrect: add color - see https://bugzilla.mozilla.org/show_bug.cgi?id=1507879#c5
   * [x] domrect: add buttons, progress bar etc - see https://privacycheck.sec.lrz.de/active/fp_gcr/fp_getclientrects.html
   * [x] FYI: [mathml](https://privacycheck.sec.lrz.de/active/fp_ml/fp_ml.html) and [emojis](https://privacycheck.sec.lrz.de/active/fp_e/fp_emoji.html)

* **Audio**
   * [x] audioContext properties
   * [x] two more openWPM tests
   * [x] output red or green `RFP` on outputLatency

* **Cookies & Storage**
   * [x] cookie notation to state it is set and read by `javascript`
   * [x] don't use generic ids that get blocked by filterlists
   * [x] differentiate between session and persistent cookies
   * [ ] lots of tests to finish etc
   * [ ] add in a "zombie" section - [temp PoC](https://ghacksuserjs.github.io/TorZillaPrint/sanitizing.html) used in a different issue I was checking

* **Fonts**
   * [x] test: detect document fonts
   * [x] test: detect default proportional font & sizes
   * [x] test: detect css font loading api
   * [x] test: detect woff2
   * [x] test: unicode glyphs
   * [x] test: unicode glyphs using clientrect
   * [x] test: fingerprintjs2
   * [x] test: extras page: monsta font list: work in progress
   * [x] font list: include all items from Tor Browser Mac and Windows whitelists
   * [x] font list: include all items from Tor Browser Linux default language fonts
   * [x] font list: fixup misspelling of `Microsoft JengHei UI` -> `Microsoft JhengHei UI`
   * [x] font list: include Tor Browser's bundled `EmojiOne Mozilla`
   * [x] font list: include Mozilla's bundled `Twemoji Mozilla`
   * [x] font list: build in handling multiple lists
   * [x] font list: build in handling lists on different pages
   * [x] font list: determine lists by os
   * [x] font list: output hyperlinks for lists
   * [x] font code: build the fontList array once (from the text file): used in two tests
   * [x] font code: text file read: ignore zero-length lines
   * [x] font code: text file read: trim each line and, ignore multi whitespace empty lines
   * [x] font code: text file read: ignore comment `//` lines: I can now document each list
   * [x] font code: array: sort
   * [x] font code: array: remove duplicates
   * [x] font code: move codepoints.txt to hard-coded array: faster: now it always beats the fontList which can now be a much smaller txt file: had a bit of a race going on there as to whether the codepoints would be ready in time
   * [x] font code: build the codepoint->testString only once
   * [x] font code: improve fallback font testString by appending unicode from glyphs test
   * [x] font code: improve fallback font testString by appending original fpjs2 string
   * [x] font code: detect the fontList Array is filled and stable using a setInterval
        * rather than using a 1500ms timer to make sure it was downloaded
        * now the tests start as quick as 150ms (FF), 400ms (TB)
   * [ ] font code: fallback font first run: investigate further
        * example: when document fonts are blocked, the first run misses fonts it picks up on subsequent tests: currently mitigated by doing a 3-font "priming" run: but this is not an elegant solution
   * [ ] font list: build the lists: win, mac, android, linux - see #43 
   * [ ] font list: cleanup monsta list - see #43
   * [ ] test: default font family: serif, sans-serif, monospace
   * [ ] test: detect selected font versions: Times New Roman, Arial [thru unicode changes per version]

* **Devices**
   * [ ] regression test: add in plugins test (including explicitly checking Flash by name)
   * [ ] regression test: add in mime types test

* **Timing Section**
   * [ ] various timing checks: to make sure things are rounded to 100ms: got a ton of these

* **Other**
   * [x] mathml detection
   * [x] WASM detection
   * [ ] page visibility API
   * [ ] fetch API
   * [ ] web request API detection (payments)
   * [ ] AOM (accessability object model)
   * [ ] SVG: enabled/disabled, but also specifically look at
      - SVGTextContentElement.prototype.getComputedTextLength
      - SVGPathElement.prototype.getTotalLength
      - SVGGeometryElement.getPointAtLength()

* **Extras**
   * [ ] widget / form controls - see http://stephenhorlander.com/form-controls.html
   * [ ] element entropy (i.e non-widget / form controls)

...

**Comment by kkapsner** [comment]
You could simply run ```canvas.createHashes(window)``` twice and compare the values you get in the two promises.

**Comment by Thorin-Oakenpants** [comment]
@kkapsner : not sure if you saw my edits to the first post - Should we upgrade the domrect tests: both here and at https://canvasblocker.kkapsner.de/test/domRectTest.html (we should keep in sync)? add color? add objects like progress bars, selects?

**Comment by kkapsner** [comment]
No - I did not see your edits.

You can use the CB detection test.
I'm not sure why colours should affect the domRect Hash but I do not mind adding them. They would not hurt.

Other HTML elements like progress bars and selects seem like a good idea. I will update my test page.

**Comment by kkapsner** [comment]
I improved my test a little bit. You can check it out.

**Comment by Thorin-Oakenpants** [comment]
cool :) now I just need to find time to make the test here the same

**Comment by Thorin-Oakenpants** [comment]
@kkapsner I just noticed something in Canvas

TB 8.0* (and earlier) report
- getContext: 2d: supported, webgl: not supported, webgl2: not supported
- [webgl] readPixels	webgl not supported

^^ that's to be expected

TB 8.5a10 (and maybe earlier)
- getContext: 2d: supported, webgl: supported, webgl2: supported
- [webgl] readPixels	error while testing

^^ so, assuming they enabled WebGL, what is causing the error? Just something to look at if you get time - I'm sure the result is what they wanted: that is TB is still blocking the entropy on this, but reducing web breakage. I haven't looked at all the changes, but it would nice to find out (or the code could be more elegant: it's already elegant, but maybe output an error code if it can be trapped: = more entropy in out tests = better)

Cheers :beer:

**Comment by Thorin-Oakenpants** [comment]
PS: Also, only going thru you, so that you're aware and our code is always in "sync"

![Untitled-1](https://user-images.githubusercontent.com/16656956/56007043-d0ed3f80-5cc6-11e9-8f1d-acd0b0a6d2f8.png)

**Comment by kkapsner** [comment]
The <unavailable> is a Firefox thing. Can you please check the console of the page (just hit Shift+Ctrl+K)? There you should be able to see the error message.

**Comment by Thorin-Oakenpants** [comment]
Yeah, sorry: I could just output the e.name - bit lazy and tired and overworked :) Just want to always include you in all things canvas/domrect/audio

```js
Error: Permission denied to access property "createBuffer"
Stack trace:
getFilledWebGlContext@https://ghacksuserjs.github.io/TorZillaPrint/js/canvas.js:230:11
value@https://ghacksuserjs.github.io/TorZillaPrint/js/canvas.js:138:25
createHashes/finished</<@https://ghacksuserjs.github.io/TorZillaPrint/js/canvas.js:273:28
createHashes/finished<@https://ghacksuserjs.github.io/TorZillaPrint/js/canvas.js:268:14
createHashes@https://ghacksuserjs.github.io/TorZillaPrint/js/canvas.js:267:32
runCanvas/<@https://ghacksuserjs.github.io/TorZillaPrint/js/canvas.js:317:21
```

**Comment by kkapsner** [comment]
So you just want the error message in the displayValue? That's easy:```
displayValue = "error while testing: " + e.message;
```

Should I change it or do you?

**Comment by Thorin-Oakenpants** [comment]
Yeah, sorry, was kinda talking to myself. I tried e.name yesterday and it's not very helpful. `e.message` (didn't know that property was there - thanks :+1: ) seems alright (even if it relates to our code rather than a nice message).

e.name `Error`
e,message `Permission denied to access property "createBuffer"` 

I'll use `displayValue = e.name +": "+e.message;` for now. It's just a TB thing, but **error entropy** is **important**.

FWIW Panopticlick returns "undetermined" for their "webgl hash" (whatever they include in that, it obviously errors out). Before it used to return an all zeros hash. So they fail more gracefully, but less info/entropy (which probably makes no difference - given only TB would do this, IDK)

**Comment by Thorin-Oakenpants** [comment]
> [1] I'll have to look it up, but RFP doesn't cover readPixels IIRC

Yup, https://bugzilla.mozilla.org/show_bug.cgi?id=1428034 which is why TB are still blocking that

**Comment by Thorin-Oakenpants** [comment]
@kkapsner I'm not entirely sure how to do this... for consistency and also generic functions (such as re-running section outputs, clearing section data, and down the track for exporting/importing data for comparisons), I would like to use `id` rather than `class`. Canvas is the only section that uses class to output the results

Looking at the code I'm not sure what to do. A search for the string `class` comes up with 9 items, but I now it;s not as simple (or even possible) to just change those. When and if you have time, could you help me out, TIA

**Comment by kkapsner** [comment]
You must not change the "class" string in the file as it's not related.

There are actually only two places you have to change:
1. your rerun portion: https://github.com/ghacksuserjs/TorZillaPrint/blob/master/js/canvas.js#L315
2. the place where I write the data to the table: https://github.com/ghacksuserjs/TorZillaPrint/blob/master/js/canvas.js#L301

The first is clear what to do and in the second the "." has to be changed to a "#".

**Comment by kkapsner** [comment]
But actually I'm not sure if this is a good idea.
I wrote the code so it can be run within different contexts (in the normal window, in an iframe, in a different tab etc.) and you then would have different tables for the different contexts.

For the rerun reset I would give all the elements that have to be reset an additional class (e.g. "result") which you then can reset easily.

**Comment by Thorin-Oakenpants** [comment]
Thanks :beer: 

The rerun function would be removed entirely, as it becomes a global call: https://github.com/ghacksuserjs/TorZillaPrint/blob/master/js/generic.js#L71

So, as simple as editing one character? I have so much to learn. I'll have to think about it now. I can always add extra code for exporting the hashes for compare, and stay in sync with your code (and down the track I do want iframe tests added).

Thanks for your sharing your knowledge :) Much appreciated

**Comment by kkapsner** [comment]
With the "result"-class approach your clear code can become much simpler and better to maintain.
You would only have to select the parent node of the section you want to clear and then get all elements with that class within it. So no need to keep track of every id within this function.

This one character is just the CSS-selector difference between id and class.

**Comment by claustromaniac** [comment]
:jeans:, in case you didn't notice, I sneaked in code for working with base64 some months ago (f56aeed and 7244d63). When whoever (likely you) puts the necessary ui elements in place, you just need to use those functions to convert the strings to and from base64. For exporting and importing results I don't know if you want to use hashes or not. If not, you may want to use the [JSON api](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON) to make that part simpler.

**Comment by Thorin-Oakenpants** [comment]
I'm not sure why I didn't think of it before. I just added an id to each of the canvas outputs, so now I can use the generic outputSection(name) for canvas the same as all the other sections with rerun buttons

I know it's not as sexy or as efficient as it could be (the clearing fields on re-runs), i.e I just use an array of the ids and clear them but 1) its important to clear and delay slightly so the end-user is aware something changed and 2) it works and 3) all my clear and re-run code is in one place

Maybe down the track I can improve it and do away with listing ids per section in arrays. Those arrays are going to add up: https://github.com/ghacksuserjs/TorZillaPrint/blob/master/js/generic.js#L71 as I add in more rerun buttons.

**Comment by Thorin-Oakenpants** [comment]
@kkapsner 

OK,,  so now that every section has a re-run button, that means each section needs to be cleared (but not always every item). But instead of clearing an array, I want to know how to do this

```html
<table id="1">
<tr><td>cookies</td><td class="c" id="test1"></td></tr>
<tr><td>cookie test</td><td class="c" id="test2"></td></tr>
<tr><td>local storage</td><td class="c" id="test3"></td></tr>
<tr><td>local storage test</td><td class="c" id="test4"></td></tr>
</table>

<table id="2">
<tr><td>language</td><td class="c" id="nLanguagues"></td></tr>
<tr><td>locale</td><td class="c" id="localeTest"></td></tr>
<tr><td>date</td><td class="c" id="dteSomething"></td></tr>
<tr><td>geo</td><td class="c" id="geoEnabled"></td></tr>
</table>
```

and so on. How do I clear table 1 class c? I would pass the class name as well as the table, since some sections have more than 1 rerun button. So in general I would use "c", but a secondary run section the td's would use e.g "c2"

```
function clearTable(tbl, cls) {
   // what is the magic one liner to go here?
}
```

Thanks. I can code it in several lines, I think, but you use `.` and `#` and make so compact and efficient. I'm missing a trick here - TIA

**Comment by claustromaniac** [comment]
```js
function clearSection(tbl, cls) {
   tbl.querySelector(`.${cls}`);
}
```

**Comment by claustromaniac** [comment]
```
function clearSection(tbl, cls) {
   for(const e of tbl.getElementsByClassName(cls)) {
      e.textContent = '';
   }
}
```

**Comment by claustromaniac** [comment]
`querySelectorAll` variant
```js
function clearSection(tbl, cls) {
   tbl.querySelectorAll(`.${cls}`).forEach(e => {
     e.textContent = '';
   });
}
```

**Comment by Thorin-Oakenpants** [comment]
Which one is quickest? You gave me ~~two~~ three answers but didn't say anything about them, much :)

I'll try em tomorrow (not timing them of course), but this is so much better than maintaining stupid array lists. Now when I add a new table row, the class="c" is all I need for it to get cleared

---

not sure about forgoing a function. I still need to pass the class name to it

**Comment by claustromaniac** [comment]
> Which one is quickest?

Dunno. I'd guess the `querySelectorAll` variant should be faster since it returns a static NodeList. The last snippet is probably what @kkapsner was referring to. I guess web developers would find that one more intuitive (I'm not one, so IDK, and I don't care anyway).

**Comment by Thorin-Oakenpants** [comment]
yeah, I can do it all in one, psuedo code off the top of my head

```js
function outputSection(tbl, cls) {
	tbl.querySelectorAll(`.${cls}`).forEach(e => {
		e.innerHTML = "&nbsp"; // &nbsp stops line height jitter
	});
	setTimeout(function(){
		if (tbl == "1") {outputScreen()};
		if (tbl == "2") {outputUA();outputMath()};
		if (tbl == "3") {outputMath()};
		if (tbl == "4") {outputLanguage()};

		if (tbl == "10" && cls=="c1") {outputFonts1()}; // is that right for `AND`
		if (tbl == "18") {outputMisc()};
	}, 170);
	// don't delay this one
	if (tbl == "10" && cls=="c2") {outputFonts2()};
}
```

**Comment by Thorin-Oakenpants** [comment]
I'll save a tiny bit of bytes (see what I did there!) .. since `class="c" ` for each item is probably about the same or shorter than most id names.

What it will really save me, is having to worry about keeping the lists of things to clear up to date

**Comment by Thorin-Oakenpants** [comment]
TypeError: tbl.querySelectorAll is not a function
TypeError: tbl.getElementsByClassName is not a function

```js
/* BUTTONS: (re)GENERATE SECTIONS */
function outputSectionTest(tbl, cls) {
	// clear elements
	for(const e of tbl.getElementsByClassName(cls)) {
		e.innerHTML = "&nbsp";
	};
	tbl.querySelectorAll(`.${cls}`).forEach(e => {
		// &nbsp stops line height jitter
		e.innerHTML = "&nbsp";
	});
	// delay output so users can see something happened
	setTimeout(function(){
		//if (tbl == "1") {outputScreen()};
	}, 170);
	// don't delay this one

};
```

**Comment by claustromaniac** [comment]
`tbl` needs to be the table element (the object returned by `document.getElementById(tableId)`.
It is already present in the `dom` interface that I added long ago as `dom.id`.

In other words, you need to call the function like this for testing:
```js
let table = document.getElementById('tableId');
outputSectionTest(table, cls);
```
but in the actual code this would suffice:
```js
whateverYouNameTheFunction(dom.tableId, cls);
```

**Comment by Thorin-Oakenpants** [comment]
I already sorted it that out :) And then I was passing `1` instead of `tbl1` and getting a null :) I am always so impatient. But at least this way I learn

**Comment by claustromaniac** [comment]
[`textContent` is better than `innerHTML`.](https://stackoverflow.com/questions/21311299/nodevalue-vs-innerhtml-and-textcontent-how-to-choose)

**Comment by Thorin-Oakenpants** [comment]
^^OK

**Comment by claustromaniac** [comment]
> I already sorted it that out :) And then I was passing 1 instead of tbl1 and getting a null :) I am always so impatient. But at least this way I learn

It's the best way to learn these things. You can read dozens of books on the subject, but programming is more about skill, and skill is only earned through experience. We self-taughts know that well.

**Comment by Thorin-Oakenpants** [comment]
I know. Anyway, can;t get past the stupid xxx is a null

**Comment by Thorin-Oakenpants** [comment]
Here's the button
```html
<button class="btn1" onClick="outputSectionTest(`tbl1`, `c`)">[ re-run tests ]</button>
```

here's the function
```js
function outputSectionTest(id, cls) {
	// clear elements, &nbsp stops line height jitter
	let tbl = document.getElementById(id);
	tbl.querySelectorAll(`.${cls}`).forEach(e => {
		e.textContent = "&nbsp";
	});
	// delay output so users can see something happened
	setTimeout(function(){
		if (tbl == "tbl1") {outputScreen()};
	}, 170);
};
```

Here's the error. you suck, null null null, TypeError: tbl is null, nah-nah-nah-nah

**Comment by Thorin-Oakenpants** [comment]
OK .. its tb1 ... not tbL1 .. i need MOAR coffee

**Comment by Thorin-Oakenpants** [comment]
and .textContent is no good. I want to add a space not the letters &nbsp

All working now

**Comment by claustromaniac** [comment]
> 		// &nbsp stops line height jitter

I'm not sure what you meant by that.

> and .textContent is no good. I want to add a space not the letters &nbsp

Have you with tried `.textContent = ' '` ? (literal space)

**Comment by Thorin-Oakenpants** [comment]
I need to insert an actual character, other wise when you can get jitter: e.g my default font is Georgia, so when populated the line height is slightly more then when empty. So when clearing everything, the section shrinks a little, then expands again = jitter. In order to output a space I need to output the HTML code `&nbsp` - I cannot do that with ` `, I actually have to insert a char.

Anyway, this is proving problematic. I cannot have two classes, the second is ignored.

e.g this means I can clear the field, but I lose my monospace font
```html
<tr class="togM"><td>atanh(0.5)</td><td class="c" class="mono" id="math1"></td></tr>
```
and this means I have monospace font, but it doesn't clear
```html
<tr class="togM"><td>atanh(0.5)</td><td class="mono" class="c" id="math1"></td></tr>
```

The same goes for canvas. Either class="c" goes first and i can empty them, and kkapsners values never get written ...or the reverse

**Comment by Thorin-Oakenpants** [comment]
I could build in a class `cm` = clear mono

**Comment by claustromaniac** [comment]
> I cannot do that with ` `, I actually have to insert a char.

That surely is true when you use `.innerHTML` because it parses the input as HTML. `.textContent` inserts literal text = no parsing = no spaces should be truncated. That's why I asked if you had tried `.textContent = ' ';`

> I cannot have two classes, the second is ignored.

try this...
```html
<tr class="togM"><td>atanh(0.5)</td><td class="c mono" id="math1"></td></tr>
```

**Comment by Thorin-Oakenpants** [comment]
OK, I only use class `mono` for results, and I always want to clear those, so I just do an extra call to clear `mono`. That solves that problem, and less classes to add. Except for the font table which has two re-run sections. The first (c1) ends up clearing the second (c2), as the second is all monospaced hashes. But I have solved that but adding .c2 to the same class as .mono in the css, and replacing it class in the html. So all done.

That just leaves canvas, where I cannot do anything with dual classes, so I stuck the array clearing code in the canvas.js file where it used to be. And DOMRect is doing a loop within a loop to clear all the output fields, so that's a special ones as well, in the domrect.js

Everything else is looking good.

**Comment by Thorin-Oakenpants** [comment]
`.textContent = ' ';` causes line heights to shrink/expand if your font is different. I'm all a bit muddled now. It seems to be OK with everything except monospace. .innerHTML means everything including mono doesn't move around

**Comment by claustromaniac** [comment]
> ... and see what happens when you rerun MATH with your method.

Yeah, I just did. Weird shit. Welp.

**Comment by Thorin-Oakenpants** [comment]
holy crap: I think this beats the previous record I had found. I was looking for something that can't be controlled by prefs, that was unique to 68+ (for browser version detection), and came across this: 16 years :) - https://bugzilla.mozilla.org/show_bug.cgi?id=205202

**Comment by Thorin-Oakenpants** [comment]
closing: see #46
