### ISSUE TITLE
ToDo: general setup

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [ghacksuserjs/TorZillaPrint#5]
Thanks for that - I should have done it to start with, but until I actually dived in and put "pen to paper" (this little project has been in the back of my head for about 12 months) I didn't really visualize just how many  sections it would take. This makes it easier to slot in new tables/colors etc (and there's going to be a few) - so cheers :beer: 

Just a couple of things:

* [x] css: some tables could do with different column widths. Some tables will get extra column(s) in the future. Can this be controlled via the css file: eg right now I want tables 2 & 7 to be at 35-65
* [x] html: whats with the all open spans e.g compare tbl1 & 2
* [x] js: i actually want to split this off into a `/js/ subdir and create a separate js file for each section - e.g screen.js, math.js
* [x] gitattributes - we should get this added ASAP. Everyone's IDEs are different. What line ending? Spaces to tabs is fine, happy with 2
* [x] apologies for my shitty JS formatting - feel free to always do direct commits to fix
* [x] add a licence - which one
* [x] readme: this should be pretty simple: its basically FF&ESR/TB specific only, only current versions, and basically anything that can be determined via first party about the browser. I want everything to be first party only (but I am kinda open to a very few third parties if need be in order to add something extra or meaningful)
* [x] travis syntax check thingie .. will someone else to set this up. I have the account/login info for the one used at ghacks.user.js. A bit over my head
   * update: forget about travis
* [x] don't know who or how this was done, but now commits get verified
* [x] repo description
* [x] repo tags
* [x] anything else we can do quickly re general setup?

Anything else, especially code wise, we should just open a new issue per section

**Comment by claustromaniac** [comment]
> gitattributes - we should get this added ASAP. Everyone's IDEs are different. What line ending? Spaces to tabs is fine, happy with 2 

is it possible to standarize indenting via gitattributes? we can use editorconfig for that, though...

> add a licence - which one

¯\\\_(ツ)_/¯ I don't care because you guys are doing most of the work anyway :rofl: (just kidding)... IDK, MIT?

> travis syntax check thingie .. will someone else to set this up. I have the account/login info for the one used at ghacks.user.js. A bit over my head

I have never used CI because I'm a casual developer and I don't need that much handholding, plus I don't give a flying fuck about badges and such. I try not to be clumsy and that's it. I can look into it though... maybe. No promises.

**Comment by claustromaniac** [comment]
BTW, since some code was borrowed from other sources, shouldn't we make sure to comply with *their* license(s)?

**Comment by Thorin-Oakenpants** [comment]
Absolutely. I'm just looking thru the js files
- the math came from here: https://github.com/plaperdr/fp-central = MIT
- css windows & screen came from Arthur: https://github.com/arthuredelstein/tordemos/blob/gh-pages/media-query-fingerprint.html = no license, although we really used https://demos.traudt.xyz/css/media/index.html and there's nothing there to say who or what license or any links
- PBMode came from :bird: and he can get stuffed ... it's about time he got plagiarized! :) Now he's one of the lads
- the scrollbar width -> os code came from :earth_asia: and I modified the zoom part of it (yet to land it)
- everything else came from code snippets all over the web as examples of what I needed to do

So do we attribute them in each js file? in a footer row in each section? eg "math code courtesy of hyperlink"? Do we add an acknowledgement footer in the readme?

**Comment by Thorin-Oakenpants** [comment]
![sample](https://user-images.githubusercontent.com/16656956/50501741-5e778d00-0a52-11e9-983a-6dff5f2319a8.png)

**Comment by Thorin-Oakenpants** [comment]
cool, now commits get "verified" ... no idea who did that

**Comment by Thorin-Oakenpants** [comment]
done, wrote a horrible draft readme .. I so suck at writing
